#dataSource
microgoople:
  db:
    driver: com.mysql.jdbc.Driver
    write:
      url: jdbc:mysql://60.205.204.218:3306/microgoople
      username: root
      password: 123456
    initialPoolSize: 1
    minPoolSize: 1
    maxPoolSize: 20
    acquireIncrement: 5
    idleConnectionTestPeriod: 60
    maxIdleTime: 180
    maxStatements: 0
    connectionTimeout: 500
    idleTimeout: 600000
    maxLifetime: 1800000
    connectionTestQuery: SELECT 1 FROM DUAL

